
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Ability : Luban.BeanBase
{
    public Ability(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        CooldownTicks = _buf.ReadLong();
        MpCost = _buf.ReadInt();
        StartupTicks = _buf.ReadLong();
        ActiveTicks = _buf.ReadLong();
        RecoveryTicks = _buf.ReadLong();
        TargetingMode = _buf.ReadString();
        Range = _buf.ReadFloat();
        ProducesEffectId = _buf.ReadInt();
        MotionSpeed = _buf.ReadFloat();
    }

    public static Ability DeserializeAbility(ByteBuf _buf)
    {
        return new Ability(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// cooldown_ticks
    /// </summary>
    public readonly long CooldownTicks;
    /// <summary>
    /// mp_cost
    /// </summary>
    public readonly int MpCost;
    /// <summary>
    /// startup_ticks
    /// </summary>
    public readonly long StartupTicks;
    /// <summary>
    /// active_ticks
    /// </summary>
    public readonly long ActiveTicks;
    /// <summary>
    /// recovery_ticks
    /// </summary>
    public readonly long RecoveryTicks;
    /// <summary>
    /// targeting_mode
    /// </summary>
    public readonly string TargetingMode;
    /// <summary>
    /// range
    /// </summary>
    public readonly float Range;
    /// <summary>
    /// produces_effect_id
    /// </summary>
    public readonly int ProducesEffectId;
    /// <summary>
    /// motion_speed
    /// </summary>
    public readonly float MotionSpeed;
   
    public const int __ID__ = 464145674;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "cooldownTicks:" + CooldownTicks + ","
        + "mpCost:" + MpCost + ","
        + "startupTicks:" + StartupTicks + ","
        + "activeTicks:" + ActiveTicks + ","
        + "recoveryTicks:" + RecoveryTicks + ","
        + "targetingMode:" + TargetingMode + ","
        + "range:" + Range + ","
        + "producesEffectId:" + ProducesEffectId + ","
        + "motionSpeed:" + MotionSpeed + ","
        + "}";
    }
}
}

