
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// polymorphic base
/// </summary>
public abstract partial class AbilityEffect : Luban.BeanBase
{
    public AbilityEffect(ByteBuf _buf) 
    {
    }

    public static AbilityEffect DeserializeAbilityEffect(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case StatusEffectApplyEffect.__ID__: return new StatusEffectApplyEffect(_buf);
            case MotionEffect.__ID__: return new MotionEffect(_buf);
            case DamageEffect.__ID__: return new DamageEffect(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

