
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Ability : Luban.BeanBase
{
    public Ability(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        CooldownTicks = _buf.ReadLong();
        MpCost = _buf.ReadInt();
        StartupTicks = _buf.ReadLong();
        ActiveTicks = _buf.ReadLong();
        RecoveryTicks = _buf.ReadLong();
        {int n0 = _buf.ReadSize(); Effects = new System.Collections.Generic.List<AbilityEffect>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AbilityEffect _e0;  _e0 = global::LOP.MasterData.AbilityEffect.DeserializeAbilityEffect(_buf); Effects.Add(_e0);}}
    }

    public static Ability DeserializeAbility(ByteBuf _buf)
    {
        return new Ability(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// cooldown_ticks
    /// </summary>
    public readonly long CooldownTicks;
    /// <summary>
    /// mp_cost
    /// </summary>
    public readonly int MpCost;
    /// <summary>
    /// startup_ticks
    /// </summary>
    public readonly long StartupTicks;
    /// <summary>
    /// active_ticks
    /// </summary>
    public readonly long ActiveTicks;
    /// <summary>
    /// recovery_ticks
    /// </summary>
    public readonly long RecoveryTicks;
    /// <summary>
    /// effects
    /// </summary>
    public readonly System.Collections.Generic.List<AbilityEffect> Effects;
   
    public const int __ID__ = 464145674;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "cooldownTicks:" + CooldownTicks + ","
        + "mpCost:" + MpCost + ","
        + "startupTicks:" + StartupTicks + ","
        + "activeTicks:" + ActiveTicks + ","
        + "recoveryTicks:" + RecoveryTicks + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

