
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Action : Luban.BeanBase
{
    public Action(ByteBuf _buf) 
    {
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        Category = _buf.ReadString();
        Duration = _buf.ReadFloat();
        CastTime = _buf.ReadFloat();
        Cooldown = _buf.ReadFloat();
        HpCost = _buf.ReadFloat();
        MpCost = _buf.ReadFloat();
    }

    public static Action DeserializeAction(ByteBuf _buf)
    {
        return new Action(_buf);
    }

    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// category
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// duration
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// cast_time
    /// </summary>
    public readonly float CastTime;
    /// <summary>
    /// cooldown
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// hp_cost
    /// </summary>
    public readonly float HpCost;
    /// <summary>
    /// mp_cost
    /// </summary>
    public readonly float MpCost;
   
    public const int __ID__ = 1955883606;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "category:" + Category + ","
        + "duration:" + Duration + ","
        + "castTime:" + CastTime + ","
        + "cooldown:" + Cooldown + ","
        + "hpCost:" + HpCost + ","
        + "mpCost:" + MpCost + ","
        + "}";
    }
}
}

