
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class ArcheryConfig : Luban.BeanBase
{
    public ArcheryConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        WavePeriodTicks = _buf.ReadInt();
        MinTargets = _buf.ReadInt();
        MaxTargets = _buf.ReadInt();
        SpawnRadius = _buf.ReadFloat();
        SpawnMinY = _buf.ReadFloat();
        SpawnMaxY = _buf.ReadFloat();
        MinSeparation = _buf.ReadFloat();
        TrapRatioMin = _buf.ReadFloat();
        TrapRatioMax = _buf.ReadFloat();
        ShakeFreeSeconds = _buf.ReadFloat();
        ShakeRampSeconds = _buf.ReadFloat();
        ShakeMaxDegrees = _buf.ReadFloat();
    }

    public static ArcheryConfig DeserializeArcheryConfig(ByteBuf _buf)
    {
        return new ArcheryConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// wave_period_ticks
    /// </summary>
    public readonly int WavePeriodTicks;
    /// <summary>
    /// min_targets
    /// </summary>
    public readonly int MinTargets;
    /// <summary>
    /// max_targets
    /// </summary>
    public readonly int MaxTargets;
    /// <summary>
    /// spawn_radius
    /// </summary>
    public readonly float SpawnRadius;
    /// <summary>
    /// spawn_min_y
    /// </summary>
    public readonly float SpawnMinY;
    /// <summary>
    /// spawn_max_y
    /// </summary>
    public readonly float SpawnMaxY;
    /// <summary>
    /// min_separation
    /// </summary>
    public readonly float MinSeparation;
    /// <summary>
    /// trap_ratio_min
    /// </summary>
    public readonly float TrapRatioMin;
    /// <summary>
    /// trap_ratio_max
    /// </summary>
    public readonly float TrapRatioMax;
    /// <summary>
    /// shake_free_seconds
    /// </summary>
    public readonly float ShakeFreeSeconds;
    /// <summary>
    /// shake_ramp_seconds
    /// </summary>
    public readonly float ShakeRampSeconds;
    /// <summary>
    /// shake_max_degrees
    /// </summary>
    public readonly float ShakeMaxDegrees;
   
    public const int __ID__ = 157521944;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "wavePeriodTicks:" + WavePeriodTicks + ","
        + "minTargets:" + MinTargets + ","
        + "maxTargets:" + MaxTargets + ","
        + "spawnRadius:" + SpawnRadius + ","
        + "spawnMinY:" + SpawnMinY + ","
        + "spawnMaxY:" + SpawnMaxY + ","
        + "minSeparation:" + MinSeparation + ","
        + "trapRatioMin:" + TrapRatioMin + ","
        + "trapRatioMax:" + TrapRatioMax + ","
        + "shakeFreeSeconds:" + ShakeFreeSeconds + ","
        + "shakeRampSeconds:" + ShakeRampSeconds + ","
        + "shakeMaxDegrees:" + ShakeMaxDegrees + ","
        + "}";
    }
}
}

