
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class ArcheryRange : Luban.BeanBase
{
    public ArcheryRange(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MapId = _buf.ReadInt();
        StandIndex = _buf.ReadInt();
        DistanceM = _buf.ReadFloat();
        ExposureTicks = _buf.ReadInt();
        LateralSpanM = _buf.ReadFloat();
        LateralPeriodS = _buf.ReadFloat();
    }

    public static ArcheryRange DeserializeArcheryRange(ByteBuf _buf)
    {
        return new ArcheryRange(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// map_id
    /// </summary>
    public readonly int MapId;
    /// <summary>
    /// stand_index
    /// </summary>
    public readonly int StandIndex;
    /// <summary>
    /// distance_m
    /// </summary>
    public readonly float DistanceM;
    /// <summary>
    /// exposure_ticks
    /// </summary>
    public readonly int ExposureTicks;
    /// <summary>
    /// lateral_span_m
    /// </summary>
    public readonly float LateralSpanM;
    /// <summary>
    /// lateral_period_s
    /// </summary>
    public readonly float LateralPeriodS;
   
    public const int __ID__ = 1403990439;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mapId:" + MapId + ","
        + "standIndex:" + StandIndex + ","
        + "distanceM:" + DistanceM + ","
        + "exposureTicks:" + ExposureTicks + ","
        + "lateralSpanM:" + LateralSpanM + ","
        + "lateralPeriodS:" + LateralPeriodS + ","
        + "}";
    }
}
}

