
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class ArcheryTargetKind : Luban.BeanBase
{
    public ArcheryTargetKind(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        Radius = _buf.ReadFloat();
        Points = _buf.ReadInt();
        Weight = _buf.ReadInt();
        IsTrap = _buf.ReadBool();
    }

    public static ArcheryTargetKind DeserializeArcheryTargetKind(ByteBuf _buf)
    {
        return new ArcheryTargetKind(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// radius
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// points
    /// </summary>
    public readonly int Points;
    /// <summary>
    /// weight
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// is_trap
    /// </summary>
    public readonly bool IsTrap;
   
    public const int __ID__ = -356603237;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "radius:" + Radius + ","
        + "points:" + Points + ","
        + "weight:" + Weight + ","
        + "isTrap:" + IsTrap + ","
        + "}";
    }
}
}

