
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class ArcheryRing : Luban.BeanBase
{
    public ArcheryRing(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TargetId = _buf.ReadInt();
        OuterRatio = _buf.ReadFloat();
        Points = _buf.ReadInt();
    }

    public static ArcheryRing DeserializeArcheryRing(ByteBuf _buf)
    {
        return new ArcheryRing(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// target_id
    /// </summary>
    public readonly int TargetId;
    /// <summary>
    /// outer_ratio
    /// </summary>
    public readonly float OuterRatio;
    /// <summary>
    /// points
    /// </summary>
    public readonly int Points;
   
    public const int __ID__ = -924533626;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "targetId:" + TargetId + ","
        + "outerRatio:" + OuterRatio + ","
        + "points:" + Points + ","
        + "}";
    }
}
}

