
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class ArcheryConfig : Luban.BeanBase
{
    public ArcheryConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        WavePeriodTicks = _buf.ReadInt();
        MinTargets = _buf.ReadInt();
        MaxTargets = _buf.ReadInt();
        SpawnRadius = _buf.ReadFloat();
        SpawnMinY = _buf.ReadFloat();
        SpawnMaxY = _buf.ReadFloat();
        MinSeparation = _buf.ReadFloat();
        TrapRatioMin = _buf.ReadFloat();
        TrapRatioMax = _buf.ReadFloat();
        ShakeFreeSeconds = _buf.ReadFloat();
        ShakeRampSeconds = _buf.ReadFloat();
        ShakeMaxDegrees = _buf.ReadFloat();
        RiseHeightMin = _buf.ReadFloat();
        RiseHeightMax = _buf.ReadFloat();
        StaggerTicks = _buf.ReadInt();
        RestTicks = _buf.ReadInt();
        CourseKind = _buf.ReadInt();
        RangeTargetId = _buf.ReadInt();
        StepGapTicks = _buf.ReadInt();
        MatchDurationTicks = _buf.ReadInt();
        ShakeBaseRatio = _buf.ReadFloat();
        ArrowsPerStand = _buf.ReadInt();
    }

    public static ArcheryConfig DeserializeArcheryConfig(ByteBuf _buf)
    {
        return new ArcheryConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// wave_period_ticks
    /// </summary>
    public readonly int WavePeriodTicks;
    /// <summary>
    /// min_targets
    /// </summary>
    public readonly int MinTargets;
    /// <summary>
    /// max_targets
    /// </summary>
    public readonly int MaxTargets;
    /// <summary>
    /// spawn_radius
    /// </summary>
    public readonly float SpawnRadius;
    /// <summary>
    /// spawn_min_y
    /// </summary>
    public readonly float SpawnMinY;
    /// <summary>
    /// spawn_max_y
    /// </summary>
    public readonly float SpawnMaxY;
    /// <summary>
    /// min_separation
    /// </summary>
    public readonly float MinSeparation;
    /// <summary>
    /// trap_ratio_min
    /// </summary>
    public readonly float TrapRatioMin;
    /// <summary>
    /// trap_ratio_max
    /// </summary>
    public readonly float TrapRatioMax;
    /// <summary>
    /// shake_free_seconds
    /// </summary>
    public readonly float ShakeFreeSeconds;
    /// <summary>
    /// shake_ramp_seconds
    /// </summary>
    public readonly float ShakeRampSeconds;
    /// <summary>
    /// shake_max_degrees
    /// </summary>
    public readonly float ShakeMaxDegrees;
    /// <summary>
    /// rise_height_min
    /// </summary>
    public readonly float RiseHeightMin;
    /// <summary>
    /// rise_height_max
    /// </summary>
    public readonly float RiseHeightMax;
    /// <summary>
    /// stagger_ticks
    /// </summary>
    public readonly int StaggerTicks;
    /// <summary>
    /// rest_ticks
    /// </summary>
    public readonly int RestTicks;
    /// <summary>
    /// course_kind
    /// </summary>
    public readonly int CourseKind;
    /// <summary>
    /// range_target_id
    /// </summary>
    public readonly int RangeTargetId;
    /// <summary>
    /// step_gap_ticks
    /// </summary>
    public readonly int StepGapTicks;
    /// <summary>
    /// match_duration_ticks
    /// </summary>
    public readonly int MatchDurationTicks;
    /// <summary>
    /// shake_base_ratio
    /// </summary>
    public readonly float ShakeBaseRatio;
    /// <summary>
    /// arrows_per_stand
    /// </summary>
    public readonly int ArrowsPerStand;
   
    public const int __ID__ = 157521944;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "wavePeriodTicks:" + WavePeriodTicks + ","
        + "minTargets:" + MinTargets + ","
        + "maxTargets:" + MaxTargets + ","
        + "spawnRadius:" + SpawnRadius + ","
        + "spawnMinY:" + SpawnMinY + ","
        + "spawnMaxY:" + SpawnMaxY + ","
        + "minSeparation:" + MinSeparation + ","
        + "trapRatioMin:" + TrapRatioMin + ","
        + "trapRatioMax:" + TrapRatioMax + ","
        + "shakeFreeSeconds:" + ShakeFreeSeconds + ","
        + "shakeRampSeconds:" + ShakeRampSeconds + ","
        + "shakeMaxDegrees:" + ShakeMaxDegrees + ","
        + "riseHeightMin:" + RiseHeightMin + ","
        + "riseHeightMax:" + RiseHeightMax + ","
        + "staggerTicks:" + StaggerTicks + ","
        + "restTicks:" + RestTicks + ","
        + "courseKind:" + CourseKind + ","
        + "rangeTargetId:" + RangeTargetId + ","
        + "stepGapTicks:" + StepGapTicks + ","
        + "matchDurationTicks:" + MatchDurationTicks + ","
        + "shakeBaseRatio:" + ShakeBaseRatio + ","
        + "arrowsPerStand:" + ArrowsPerStand + ","
        + "}";
    }
}
}

