
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Character : Luban.BeanBase
{
    public Character(ByteBuf _buf) 
    {
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        Speed = _buf.ReadFloat();
        JumpPower = _buf.ReadFloat();
        DefaultSkinCode = _buf.ReadString();
    }

    public static Character DeserializeCharacter(ByteBuf _buf)
    {
        return new Character(_buf);
    }

    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// speed
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// jump_power
    /// </summary>
    public readonly float JumpPower;
    /// <summary>
    /// default_skin_code
    /// </summary>
    public readonly string DefaultSkinCode;
   
    public const int __ID__ = -726803703;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "speed:" + Speed + ","
        + "jumpPower:" + JumpPower + ","
        + "defaultSkinCode:" + DefaultSkinCode + ","
        + "}";
    }
}
}

