
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class CharacterLoadout : Luban.BeanBase
{
    public CharacterLoadout(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CharacterCode = _buf.ReadString();
        Slot = _buf.ReadInt();
        AbilityId = _buf.ReadInt();
    }

    public static CharacterLoadout DeserializeCharacterLoadout(ByteBuf _buf)
    {
        return new CharacterLoadout(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// character_code
    /// </summary>
    public readonly string CharacterCode;
    /// <summary>
    /// slot
    /// </summary>
    public readonly int Slot;
    /// <summary>
    /// ability_id
    /// </summary>
    public readonly int AbilityId;
   
    public const int __ID__ = -1102452385;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "characterCode:" + CharacterCode + ","
        + "slot:" + Slot + ","
        + "abilityId:" + AbilityId + ","
        + "}";
    }
}
}

