
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class CombatConfig : Luban.BeanBase
{
    public CombatConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DodgeChanceMin = _buf.ReadFloat();
        DodgeChanceMax = _buf.ReadFloat();
        CritChanceMin = _buf.ReadFloat();
        CritChanceMax = _buf.ReadFloat();
        CritMultMin = _buf.ReadFloat();
        CritMultMax = _buf.ReadFloat();
    }

    public static CombatConfig DeserializeCombatConfig(ByteBuf _buf)
    {
        return new CombatConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// dodge_chance_min
    /// </summary>
    public readonly float DodgeChanceMin;
    /// <summary>
    /// dodge_chance_max
    /// </summary>
    public readonly float DodgeChanceMax;
    /// <summary>
    /// crit_chance_min
    /// </summary>
    public readonly float CritChanceMin;
    /// <summary>
    /// crit_chance_max
    /// </summary>
    public readonly float CritChanceMax;
    /// <summary>
    /// crit_mult_min
    /// </summary>
    public readonly float CritMultMin;
    /// <summary>
    /// crit_mult_max
    /// </summary>
    public readonly float CritMultMax;
   
    public const int __ID__ = 627620726;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dodgeChanceMin:" + DodgeChanceMin + ","
        + "dodgeChanceMax:" + DodgeChanceMax + ","
        + "critChanceMin:" + CritChanceMin + ","
        + "critChanceMax:" + CritChanceMax + ","
        + "critMultMin:" + CritMultMin + ","
        + "critMultMax:" + CritMultMax + ","
        + "}";
    }
}
}

