
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// 데미지 + 부채꼴 타게팅 형상
/// </summary>
public sealed partial class DamageEffect : AbilityEffect
{
    public DamageEffect(ByteBuf _buf)  : base(_buf) 
    {
        Amount = _buf.ReadInt();
        Range = _buf.ReadFloat();
        Angle = _buf.ReadFloat();
    }

    public static DamageEffect DeserializeDamageEffect(ByteBuf _buf)
    {
        return new DamageEffect(_buf);
    }

    public readonly int Amount;
    public readonly float Range;
    public readonly float Angle;
   
    public const int __ID__ = -855312896;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "amount:" + Amount + ","
        + "range:" + Range + ","
        + "angle:" + Angle + ","
        + "}";
    }
}
}

