
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class DodgeConfig : Luban.BeanBase
{
    public DodgeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Lives = _buf.ReadInt();
        InvulnerableSeconds = _buf.ReadFloat();
        HitRadius = _buf.ReadFloat();
        LeadSeconds = _buf.ReadFloat();
        ArenaHalf = _buf.ReadFloat();
        TileCount = _buf.ReadInt();
        FirstPatternDelaySeconds = _buf.ReadFloat();
        PatternIntervalSeconds = _buf.ReadFloat();
        OnlyKind = _buf.ReadInt();
        WarnSeconds = _buf.ReadFloat();
        BulletSpeed = _buf.ReadFloat();
        BulletRadius = _buf.ReadFloat();
        BombRadius = _buf.ReadFloat();
        BombActiveSeconds = _buf.ReadFloat();
        LaserWidth = _buf.ReadFloat();
        LaserOnSeconds = _buf.ReadFloat();
        RockSpeed = _buf.ReadFloat();
        RockRadius = _buf.ReadFloat();
        TileOnSeconds = _buf.ReadFloat();
        MinIntervalSeconds = _buf.ReadFloat();
        MinWarnSeconds = _buf.ReadFloat();
        SuddenDeathBase = _buf.ReadFloat();
        SuddenDeathGrowth = _buf.ReadFloat();
    }

    public static DodgeConfig DeserializeDodgeConfig(ByteBuf _buf)
    {
        return new DodgeConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// lives
    /// </summary>
    public readonly int Lives;
    /// <summary>
    /// invulnerable_seconds
    /// </summary>
    public readonly float InvulnerableSeconds;
    /// <summary>
    /// hit_radius
    /// </summary>
    public readonly float HitRadius;
    /// <summary>
    /// lead_seconds
    /// </summary>
    public readonly float LeadSeconds;
    /// <summary>
    /// arena_half
    /// </summary>
    public readonly float ArenaHalf;
    /// <summary>
    /// tile_count
    /// </summary>
    public readonly int TileCount;
    /// <summary>
    /// first_pattern_delay_seconds
    /// </summary>
    public readonly float FirstPatternDelaySeconds;
    /// <summary>
    /// pattern_interval_seconds
    /// </summary>
    public readonly float PatternIntervalSeconds;
    /// <summary>
    /// only_kind
    /// </summary>
    public readonly int OnlyKind;
    /// <summary>
    /// warn_seconds
    /// </summary>
    public readonly float WarnSeconds;
    /// <summary>
    /// bullet_speed
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// bullet_radius
    /// </summary>
    public readonly float BulletRadius;
    /// <summary>
    /// bomb_radius
    /// </summary>
    public readonly float BombRadius;
    /// <summary>
    /// bomb_active_seconds
    /// </summary>
    public readonly float BombActiveSeconds;
    /// <summary>
    /// laser_width
    /// </summary>
    public readonly float LaserWidth;
    /// <summary>
    /// laser_on_seconds
    /// </summary>
    public readonly float LaserOnSeconds;
    /// <summary>
    /// rock_speed
    /// </summary>
    public readonly float RockSpeed;
    /// <summary>
    /// rock_radius
    /// </summary>
    public readonly float RockRadius;
    /// <summary>
    /// tile_on_seconds
    /// </summary>
    public readonly float TileOnSeconds;
    /// <summary>
    /// min_interval_seconds
    /// </summary>
    public readonly float MinIntervalSeconds;
    /// <summary>
    /// min_warn_seconds
    /// </summary>
    public readonly float MinWarnSeconds;
    /// <summary>
    /// sudden_death_base
    /// </summary>
    public readonly float SuddenDeathBase;
    /// <summary>
    /// sudden_death_growth
    /// </summary>
    public readonly float SuddenDeathGrowth;
   
    public const int __ID__ = -2040151591;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "lives:" + Lives + ","
        + "invulnerableSeconds:" + InvulnerableSeconds + ","
        + "hitRadius:" + HitRadius + ","
        + "leadSeconds:" + LeadSeconds + ","
        + "arenaHalf:" + ArenaHalf + ","
        + "tileCount:" + TileCount + ","
        + "firstPatternDelaySeconds:" + FirstPatternDelaySeconds + ","
        + "patternIntervalSeconds:" + PatternIntervalSeconds + ","
        + "onlyKind:" + OnlyKind + ","
        + "warnSeconds:" + WarnSeconds + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "bulletRadius:" + BulletRadius + ","
        + "bombRadius:" + BombRadius + ","
        + "bombActiveSeconds:" + BombActiveSeconds + ","
        + "laserWidth:" + LaserWidth + ","
        + "laserOnSeconds:" + LaserOnSeconds + ","
        + "rockSpeed:" + RockSpeed + ","
        + "rockRadius:" + RockRadius + ","
        + "tileOnSeconds:" + TileOnSeconds + ","
        + "minIntervalSeconds:" + MinIntervalSeconds + ","
        + "minWarnSeconds:" + MinWarnSeconds + ","
        + "suddenDeathBase:" + SuddenDeathBase + ","
        + "suddenDeathGrowth:" + SuddenDeathGrowth + ","
        + "}";
    }
}
}

