
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class DodgeStage : Luban.BeanBase
{
    public DodgeStage(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        DurationSeconds = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); Kinds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Kinds.Add(_e0);}}
        BaseIntensity = _buf.ReadFloat();
        Tighten = _buf.ReadFloat();
        IntervalSeconds = _buf.ReadFloat();
    }

    public static DodgeStage DeserializeDodgeStage(ByteBuf _buf)
    {
        return new DodgeStage(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// duration_seconds
    /// </summary>
    public readonly float DurationSeconds;
    /// <summary>
    /// kinds
    /// </summary>
    public readonly System.Collections.Generic.List<int> Kinds;
    /// <summary>
    /// base_intensity
    /// </summary>
    public readonly float BaseIntensity;
    /// <summary>
    /// tighten
    /// </summary>
    public readonly float Tighten;
    /// <summary>
    /// interval_seconds
    /// </summary>
    public readonly float IntervalSeconds;
   
    public const int __ID__ = -1159277177;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "durationSeconds:" + DurationSeconds + ","
        + "kinds:" + Luban.StringUtil.CollectionToString(Kinds) + ","
        + "baseIntensity:" + BaseIntensity + ","
        + "tighten:" + Tighten + ","
        + "intervalSeconds:" + IntervalSeconds + ","
        + "}";
    }
}
}

