
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class FlappyConfig : Luban.BeanBase
{
    public FlappyConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ForwardSpeed = _buf.ReadFloat();
        FlapImpulse = _buf.ReadFloat();
        Gravity = _buf.ReadFloat();
        MaxFallSpeed = _buf.ReadFloat();
        BodyRadius = _buf.ReadFloat();
        BodyHeight = _buf.ReadFloat();
        Restitution = _buf.ReadFloat();
    }

    public static FlappyConfig DeserializeFlappyConfig(ByteBuf _buf)
    {
        return new FlappyConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// forward_speed
    /// </summary>
    public readonly float ForwardSpeed;
    /// <summary>
    /// flap_impulse
    /// </summary>
    public readonly float FlapImpulse;
    /// <summary>
    /// gravity
    /// </summary>
    public readonly float Gravity;
    /// <summary>
    /// max_fall_speed
    /// </summary>
    public readonly float MaxFallSpeed;
    /// <summary>
    /// body_radius
    /// </summary>
    public readonly float BodyRadius;
    /// <summary>
    /// body_height
    /// </summary>
    public readonly float BodyHeight;
    /// <summary>
    /// restitution
    /// </summary>
    public readonly float Restitution;
   
    public const int __ID__ = 1154294080;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "forwardSpeed:" + ForwardSpeed + ","
        + "flapImpulse:" + FlapImpulse + ","
        + "gravity:" + Gravity + ","
        + "maxFallSpeed:" + MaxFallSpeed + ","
        + "bodyRadius:" + BodyRadius + ","
        + "bodyHeight:" + BodyHeight + ","
        + "restitution:" + Restitution + ","
        + "}";
    }
}
}

