
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class GameMap : Luban.BeanBase
{
    public GameMap(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        GameModeId = _buf.ReadInt();
        Code = _buf.ReadString();
        ScenePath = _buf.ReadString();
    }

    public static GameMap DeserializeGameMap(ByteBuf _buf)
    {
        return new GameMap(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// game_mode_id
    /// </summary>
    public readonly int GameModeId;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// scene_path
    /// </summary>
    public readonly string ScenePath;
   
    public const int __ID__ = 1469029354;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "gameModeId:" + GameModeId + ","
        + "code:" + Code + ","
        + "scenePath:" + ScenePath + ","
        + "}";
    }
}
}

