
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class GameMode : Luban.BeanBase
{
    public GameMode(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        MinPlayers = _buf.ReadInt();
        MaxPlayers = _buf.ReadInt();
        ScenePath = _buf.ReadString();
    }

    public static GameMode DeserializeGameMode(ByteBuf _buf)
    {
        return new GameMode(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// min_players
    /// </summary>
    public readonly int MinPlayers;
    /// <summary>
    /// max_players
    /// </summary>
    public readonly int MaxPlayers;
    /// <summary>
    /// scene_path
    /// </summary>
    public readonly string ScenePath;
   
    public const int __ID__ = -1704717099;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "minPlayers:" + MinPlayers + ","
        + "maxPlayers:" + MaxPlayers + ","
        + "scenePath:" + ScenePath + ","
        + "}";
    }
}
}

