
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// 넉백 — 공격자 반대로 밀기(지수 감쇠)
/// </summary>
public sealed partial class KnockbackEffect : AbilityEffect
{
    public KnockbackEffect(ByteBuf _buf)  : base(_buf) 
    {
        Strength = _buf.ReadFloat();
        DurationTicks = _buf.ReadInt();
        DecayPerTick = _buf.ReadFloat();
    }

    public static KnockbackEffect DeserializeKnockbackEffect(ByteBuf _buf)
    {
        return new KnockbackEffect(_buf);
    }

    public readonly float Strength;
    public readonly int DurationTicks;
    public readonly float DecayPerTick;
   
    public const int __ID__ = 1989435660;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "strength:" + Strength + ","
        + "durationTicks:" + DurationTicks + ","
        + "decayPerTick:" + DecayPerTick + ","
        + "}";
    }
}
}

