
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class MotionEffect : AbilityEffect
{
    public MotionEffect(ByteBuf _buf)  : base(_buf) 
    {
        Speed = _buf.ReadFloat();
    }

    public static MotionEffect DeserializeMotionEffect(ByteBuf _buf)
    {
        return new MotionEffect(_buf);
    }

    public readonly float Speed;
   
    public const int __ID__ = -1576232697;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "speed:" + Speed + ","
        + "}";
    }
}
}

