
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class PanchigiSetup : Luban.BeanBase
{
    public PanchigiSetup(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CoinCount = _buf.ReadInt();
        Formation = _buf.ReadString();
    }

    public static PanchigiSetup DeserializePanchigiSetup(ByteBuf _buf)
    {
        return new PanchigiSetup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// coin_count
    /// </summary>
    public readonly int CoinCount;
    /// <summary>
    /// formation
    /// </summary>
    public readonly string Formation;
   
    public const int __ID__ = -1113212460;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "coinCount:" + CoinCount + ","
        + "formation:" + Formation + ","
        + "}";
    }
}
}

