
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class PanchigiConfig : Luban.BeanBase
{
    public PanchigiConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        StrikePowerMax = _buf.ReadFloat();
        RestSpeedEpsilon = _buf.ReadFloat();
        RestAngularEpsilon = _buf.ReadFloat();
        RestTicks = _buf.ReadInt();
        AimTimeoutSec = _buf.ReadFloat();
        MatchTurnLimit = _buf.ReadInt();
        DropOutLimit = _buf.ReadInt();
        ForceMultiplier = _buf.ReadFloat();
        HorizontalForceMultiplier = _buf.ReadFloat();
        FalloffRate = _buf.ReadFloat();
        CoverageSamples = _buf.ReadInt();
        HoldTimeMax = _buf.ReadFloat();
    }

    public static PanchigiConfig DeserializePanchigiConfig(ByteBuf _buf)
    {
        return new PanchigiConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// strike_power_max
    /// </summary>
    public readonly float StrikePowerMax;
    /// <summary>
    /// rest_speed_epsilon
    /// </summary>
    public readonly float RestSpeedEpsilon;
    /// <summary>
    /// rest_angular_epsilon
    /// </summary>
    public readonly float RestAngularEpsilon;
    /// <summary>
    /// rest_ticks
    /// </summary>
    public readonly int RestTicks;
    /// <summary>
    /// aim_timeout_sec
    /// </summary>
    public readonly float AimTimeoutSec;
    /// <summary>
    /// match_turn_limit
    /// </summary>
    public readonly int MatchTurnLimit;
    /// <summary>
    /// drop_out_limit
    /// </summary>
    public readonly int DropOutLimit;
    /// <summary>
    /// force_multiplier
    /// </summary>
    public readonly float ForceMultiplier;
    /// <summary>
    /// horizontal_force_multiplier
    /// </summary>
    public readonly float HorizontalForceMultiplier;
    /// <summary>
    /// falloff_rate
    /// </summary>
    public readonly float FalloffRate;
    /// <summary>
    /// coverage_samples
    /// </summary>
    public readonly int CoverageSamples;
    /// <summary>
    /// hold_time_max
    /// </summary>
    public readonly float HoldTimeMax;
   
    public const int __ID__ = -598872373;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "strikePowerMax:" + StrikePowerMax + ","
        + "restSpeedEpsilon:" + RestSpeedEpsilon + ","
        + "restAngularEpsilon:" + RestAngularEpsilon + ","
        + "restTicks:" + RestTicks + ","
        + "aimTimeoutSec:" + AimTimeoutSec + ","
        + "matchTurnLimit:" + MatchTurnLimit + ","
        + "dropOutLimit:" + DropOutLimit + ","
        + "forceMultiplier:" + ForceMultiplier + ","
        + "horizontalForceMultiplier:" + HorizontalForceMultiplier + ","
        + "falloffRate:" + FalloffRate + ","
        + "coverageSamples:" + CoverageSamples + ","
        + "holdTimeMax:" + HoldTimeMax + ","
        + "}";
    }
}
}

