
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Queue : Luban.BeanBase
{
    public Queue(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        RatingRangeStart = _buf.ReadInt();
        RatingRangeMax = _buf.ReadInt();
        RatingRelaxPerSec = _buf.ReadInt();
        HasVisibleRank = _buf.ReadBool();
        GameModeSelector = _buf.ReadString();
        MapSelector = _buf.ReadString();
        {int n0 = _buf.ReadSize(); AllowedGameModeIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AllowedGameModeIds.Add(_e0);}}
        MaxWaitSeconds = _buf.ReadInt();
    }

    public static Queue DeserializeQueue(ByteBuf _buf)
    {
        return new Queue(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// rating_range_start
    /// </summary>
    public readonly int RatingRangeStart;
    /// <summary>
    /// rating_range_max
    /// </summary>
    public readonly int RatingRangeMax;
    /// <summary>
    /// rating_relax_per_sec
    /// </summary>
    public readonly int RatingRelaxPerSec;
    /// <summary>
    /// has_visible_rank
    /// </summary>
    public readonly bool HasVisibleRank;
    /// <summary>
    /// game_mode_selector
    /// </summary>
    public readonly string GameModeSelector;
    /// <summary>
    /// map_selector
    /// </summary>
    public readonly string MapSelector;
    /// <summary>
    /// allowed_game_mode_ids
    /// </summary>
    public readonly System.Collections.Generic.List<int> AllowedGameModeIds;
    /// <summary>
    /// max_wait_seconds
    /// </summary>
    public readonly int MaxWaitSeconds;
   
    public const int __ID__ = 78391537;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "ratingRangeStart:" + RatingRangeStart + ","
        + "ratingRangeMax:" + RatingRangeMax + ","
        + "ratingRelaxPerSec:" + RatingRelaxPerSec + ","
        + "hasVisibleRank:" + HasVisibleRank + ","
        + "gameModeSelector:" + GameModeSelector + ","
        + "mapSelector:" + MapSelector + ","
        + "allowedGameModeIds:" + Luban.StringUtil.CollectionToString(AllowedGameModeIds) + ","
        + "maxWaitSeconds:" + MaxWaitSeconds + ","
        + "}";
    }
}
}

