
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Skin : Luban.BeanBase
{
    public Skin(ByteBuf _buf) 
    {
        Code = _buf.ReadString();
        Name = _buf.ReadString();
    }

    public static Skin DeserializeSkin(ByteBuf _buf)
    {
        return new Skin(_buf);
    }

    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = 2578845;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

