
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class SkydiveConfig : Luban.BeanBase
{
    public SkydiveConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SpreadFallSpeed = _buf.ReadFloat();
        DiveFallSpeed = _buf.ReadFloat();
        GlideFallSpeed = _buf.ReadFloat();
        SpreadMoveSpeed = _buf.ReadFloat();
        DiveMoveSpeed = _buf.ReadFloat();
        GlideMoveSpeed = _buf.ReadFloat();
        SpreadTurnAccel = _buf.ReadFloat();
        DiveTurnAccel = _buf.ReadFloat();
        GlideTurnAccel = _buf.ReadFloat();
        FallApproach = _buf.ReadFloat();
        PostureRate = _buf.ReadFloat();
        BodyRadius = _buf.ReadFloat();
        BodyHeight = _buf.ReadFloat();
        GroundY = _buf.ReadFloat();
        StaminaMax = _buf.ReadFloat();
        GlideDrain = _buf.ReadFloat();
        GroundRecover = _buf.ReadFloat();
        EmergencyGlideTime = _buf.ReadFloat();
        GroundMoveSpeed = _buf.ReadFloat();
        GroundAccel = _buf.ReadFloat();
        JumpPower = _buf.ReadFloat();
        PoseClearance = _buf.ReadFloat();
    }

    public static SkydiveConfig DeserializeSkydiveConfig(ByteBuf _buf)
    {
        return new SkydiveConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// spread_fall_speed
    /// </summary>
    public readonly float SpreadFallSpeed;
    /// <summary>
    /// dive_fall_speed
    /// </summary>
    public readonly float DiveFallSpeed;
    /// <summary>
    /// glide_fall_speed
    /// </summary>
    public readonly float GlideFallSpeed;
    /// <summary>
    /// spread_move_speed
    /// </summary>
    public readonly float SpreadMoveSpeed;
    /// <summary>
    /// dive_move_speed
    /// </summary>
    public readonly float DiveMoveSpeed;
    /// <summary>
    /// glide_move_speed
    /// </summary>
    public readonly float GlideMoveSpeed;
    /// <summary>
    /// spread_turn_accel
    /// </summary>
    public readonly float SpreadTurnAccel;
    /// <summary>
    /// dive_turn_accel
    /// </summary>
    public readonly float DiveTurnAccel;
    /// <summary>
    /// glide_turn_accel
    /// </summary>
    public readonly float GlideTurnAccel;
    /// <summary>
    /// fall_approach
    /// </summary>
    public readonly float FallApproach;
    /// <summary>
    /// posture_rate
    /// </summary>
    public readonly float PostureRate;
    /// <summary>
    /// body_radius
    /// </summary>
    public readonly float BodyRadius;
    /// <summary>
    /// body_height
    /// </summary>
    public readonly float BodyHeight;
    /// <summary>
    /// ground_y
    /// </summary>
    public readonly float GroundY;
    /// <summary>
    /// stamina_max
    /// </summary>
    public readonly float StaminaMax;
    /// <summary>
    /// glide_drain
    /// </summary>
    public readonly float GlideDrain;
    /// <summary>
    /// ground_recover
    /// </summary>
    public readonly float GroundRecover;
    /// <summary>
    /// emergency_glide_time
    /// </summary>
    public readonly float EmergencyGlideTime;
    /// <summary>
    /// ground_move_speed
    /// </summary>
    public readonly float GroundMoveSpeed;
    /// <summary>
    /// ground_accel
    /// </summary>
    public readonly float GroundAccel;
    /// <summary>
    /// jump_power
    /// </summary>
    public readonly float JumpPower;
    /// <summary>
    /// pose_clearance
    /// </summary>
    public readonly float PoseClearance;
   
    public const int __ID__ = 1641672215;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "spreadFallSpeed:" + SpreadFallSpeed + ","
        + "diveFallSpeed:" + DiveFallSpeed + ","
        + "glideFallSpeed:" + GlideFallSpeed + ","
        + "spreadMoveSpeed:" + SpreadMoveSpeed + ","
        + "diveMoveSpeed:" + DiveMoveSpeed + ","
        + "glideMoveSpeed:" + GlideMoveSpeed + ","
        + "spreadTurnAccel:" + SpreadTurnAccel + ","
        + "diveTurnAccel:" + DiveTurnAccel + ","
        + "glideTurnAccel:" + GlideTurnAccel + ","
        + "fallApproach:" + FallApproach + ","
        + "postureRate:" + PostureRate + ","
        + "bodyRadius:" + BodyRadius + ","
        + "bodyHeight:" + BodyHeight + ","
        + "groundY:" + GroundY + ","
        + "staminaMax:" + StaminaMax + ","
        + "glideDrain:" + GlideDrain + ","
        + "groundRecover:" + GroundRecover + ","
        + "emergencyGlideTime:" + EmergencyGlideTime + ","
        + "groundMoveSpeed:" + GroundMoveSpeed + ","
        + "groundAccel:" + GroundAccel + ","
        + "jumpPower:" + JumpPower + ","
        + "poseClearance:" + PoseClearance + ","
        + "}";
    }
}
}

