
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class StatusEffect : Luban.BeanBase
{
    public StatusEffect(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        DurationPolicy = _buf.ReadString();
        DurationTicks = _buf.ReadLong();
        ModStatType = _buf.ReadString();
        ModValue = _buf.ReadFloat();
        ModType = _buf.ReadString();
        StackPolicy = _buf.ReadString();
        MaxStacks = _buf.ReadInt();
    }

    public static StatusEffect DeserializeStatusEffect(ByteBuf _buf)
    {
        return new StatusEffect(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// duration_policy
    /// </summary>
    public readonly string DurationPolicy;
    /// <summary>
    /// duration_ticks
    /// </summary>
    public readonly long DurationTicks;
    /// <summary>
    /// mod_stat_type
    /// </summary>
    public readonly string ModStatType;
    /// <summary>
    /// mod_value
    /// </summary>
    public readonly float ModValue;
    /// <summary>
    /// mod_type
    /// </summary>
    public readonly string ModType;
    /// <summary>
    /// stack_policy
    /// </summary>
    public readonly string StackPolicy;
    /// <summary>
    /// max_stacks
    /// </summary>
    public readonly int MaxStacks;
   
    public const int __ID__ = 1844546627;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "durationPolicy:" + DurationPolicy + ","
        + "durationTicks:" + DurationTicks + ","
        + "modStatType:" + ModStatType + ","
        + "modValue:" + ModValue + ","
        + "modType:" + ModType + ","
        + "stackPolicy:" + StackPolicy + ","
        + "maxStacks:" + MaxStacks + ","
        + "}";
    }
}
}

