
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class StatusEffectApplyEffect : AbilityEffect
{
    public StatusEffectApplyEffect(ByteBuf _buf)  : base(_buf) 
    {
        StatusEffectId = _buf.ReadInt();
    }

    public static StatusEffectApplyEffect DeserializeStatusEffectApplyEffect(ByteBuf _buf)
    {
        return new StatusEffectApplyEffect(_buf);
    }

    public readonly int StatusEffectId;
   
    public const int __ID__ = 652034652;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "statusEffectId:" + StatusEffectId + ","
        + "}";
    }
}
}

