
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace LOP.MasterData
{
public partial class Tables
{
    /// <summary>
    /// Character
    /// </summary>
    public TbCharacter TbCharacter {get; }
    /// <summary>
    /// Skin
    /// </summary>
    public TbSkin TbSkin {get; }
    /// <summary>
    /// Item
    /// </summary>
    public TbItem TbItem {get; }
    /// <summary>
    /// StatusEffect
    /// </summary>
    public TbStatusEffect TbStatusEffect {get; }
    /// <summary>
    /// Ability
    /// </summary>
    public TbAbility TbAbility {get; }
    /// <summary>
    /// CombatConfig(전역 전투 튜닝, 서버 전용)
    /// </summary>
    public TbCombatConfig TbCombatConfig {get; }
    /// <summary>
    /// CharacterLoadout
    /// </summary>
    public TbCharacterLoadout TbCharacterLoadout {get; }
    /// <summary>
    /// GameMode
    /// </summary>
    public TbGameMode TbGameMode {get; }
    /// <summary>
    /// GameMap
    /// </summary>
    public TbMap TbMap {get; }
    /// <summary>
    /// Queue
    /// </summary>
    public TbQueue TbQueue {get; }
    /// <summary>
    /// FlappyConfig(Flappy Race 튜닝, 클&#183;서 공용)
    /// </summary>
    public TbFlappyConfig TbFlappyConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCharacter = new TbCharacter(loader("tbcharacter"));
        TbSkin = new TbSkin(loader("tbskin"));
        TbItem = new TbItem(loader("tbitem"));
        TbStatusEffect = new TbStatusEffect(loader("tbstatuseffect"));
        TbAbility = new TbAbility(loader("tbability"));
        TbCombatConfig = new TbCombatConfig(loader("tbcombatconfig"));
        TbCharacterLoadout = new TbCharacterLoadout(loader("tbcharacterloadout"));
        TbGameMode = new TbGameMode(loader("tbgamemode"));
        TbMap = new TbMap(loader("tbmap"));
        TbQueue = new TbQueue(loader("tbqueue"));
        TbFlappyConfig = new TbFlappyConfig(loader("tbflappyconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCharacter.ResolveRef(this);
        TbSkin.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbStatusEffect.ResolveRef(this);
        TbAbility.ResolveRef(this);
        TbCombatConfig.ResolveRef(this);
        TbCharacterLoadout.ResolveRef(this);
        TbGameMode.ResolveRef(this);
        TbMap.ResolveRef(this);
        TbQueue.ResolveRef(this);
        TbFlappyConfig.ResolveRef(this);
    }
}

}
