
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace LOP.MasterData
{
public partial class Tables
{
    /// <summary>
    /// Character
    /// </summary>
    public TbCharacter TbCharacter {get; }
    /// <summary>
    /// Skin
    /// </summary>
    public TbSkin TbSkin {get; }
    /// <summary>
    /// Action
    /// </summary>
    public TbAction TbAction {get; }
    /// <summary>
    /// Item
    /// </summary>
    public TbItem TbItem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCharacter = new TbCharacter(loader("tbcharacter"));
        TbSkin = new TbSkin(loader("tbskin"));
        TbAction = new TbAction(loader("tbaction"));
        TbItem = new TbItem(loader("tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCharacter.ResolveRef(this);
        TbSkin.ResolveRef(this);
        TbAction.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
}

}
