
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// Ability
/// </summary>
public partial class TbAbility
{
    private readonly System.Collections.Generic.Dictionary<int, Ability> _dataMap;
    private readonly System.Collections.Generic.List<Ability> _dataList;
    
    public TbAbility(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Ability>(n);
        _dataList = new System.Collections.Generic.List<Ability>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Ability _v;
            _v = global::LOP.MasterData.Ability.DeserializeAbility(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Ability> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Ability> DataList => _dataList;

    public Ability GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Ability Get(int key) => _dataMap[key];
    public Ability this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

