
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// Action
/// </summary>
public partial class TbAction
{
    private readonly System.Collections.Generic.Dictionary<string, Action> _dataMap;
    private readonly System.Collections.Generic.List<Action> _dataList;
    
    public TbAction(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, Action>(n);
        _dataList = new System.Collections.Generic.List<Action>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Action _v;
            _v = global::LOP.MasterData.Action.DeserializeAction(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Action> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Action> DataList => _dataList;

    public Action GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Action Get(string key) => _dataMap[key];
    public Action this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

