
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// ArcheryRange(사거리 맵의 거리별 노출)
/// </summary>
public partial class TbArcheryRange
{
    private readonly System.Collections.Generic.Dictionary<int, ArcheryRange> _dataMap;
    private readonly System.Collections.Generic.List<ArcheryRange> _dataList;
    
    public TbArcheryRange(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ArcheryRange>(n);
        _dataList = new System.Collections.Generic.List<ArcheryRange>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ArcheryRange _v;
            _v = global::LOP.MasterData.ArcheryRange.DeserializeArcheryRange(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, ArcheryRange> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ArcheryRange> DataList => _dataList;

    public ArcheryRange GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ArcheryRange Get(int key) => _dataMap[key];
    public ArcheryRange this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

