
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// ArcheryRing(과녁 동심원 띠)
/// </summary>
public partial class TbArcheryRing
{
    private readonly System.Collections.Generic.Dictionary<int, ArcheryRing> _dataMap;
    private readonly System.Collections.Generic.List<ArcheryRing> _dataList;
    
    public TbArcheryRing(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ArcheryRing>(n);
        _dataList = new System.Collections.Generic.List<ArcheryRing>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ArcheryRing _v;
            _v = global::LOP.MasterData.ArcheryRing.DeserializeArcheryRing(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, ArcheryRing> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ArcheryRing> DataList => _dataList;

    public ArcheryRing GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ArcheryRing Get(int key) => _dataMap[key];
    public ArcheryRing this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

