
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// ArcheryTargetKind(과녁 종류)
/// </summary>
public partial class TbArcheryTarget
{
    private readonly System.Collections.Generic.Dictionary<int, ArcheryTargetKind> _dataMap;
    private readonly System.Collections.Generic.List<ArcheryTargetKind> _dataList;
    
    public TbArcheryTarget(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ArcheryTargetKind>(n);
        _dataList = new System.Collections.Generic.List<ArcheryTargetKind>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ArcheryTargetKind _v;
            _v = global::LOP.MasterData.ArcheryTargetKind.DeserializeArcheryTargetKind(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, ArcheryTargetKind> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ArcheryTargetKind> DataList => _dataList;

    public ArcheryTargetKind GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ArcheryTargetKind Get(int key) => _dataMap[key];
    public ArcheryTargetKind this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

