
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// Character
/// </summary>
public partial class TbCharacter
{
    private readonly System.Collections.Generic.Dictionary<string, Character> _dataMap;
    private readonly System.Collections.Generic.List<Character> _dataList;
    
    public TbCharacter(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, Character>(n);
        _dataList = new System.Collections.Generic.List<Character>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character _v;
            _v = global::LOP.MasterData.Character.DeserializeCharacter(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Character> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Character> DataList => _dataList;

    public Character GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character Get(string key) => _dataMap[key];
    public Character this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

