
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// CharacterLoadout
/// </summary>
public partial class TbCharacterLoadout
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterLoadout> _dataMap;
    private readonly System.Collections.Generic.List<CharacterLoadout> _dataList;
    
    public TbCharacterLoadout(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterLoadout>(n);
        _dataList = new System.Collections.Generic.List<CharacterLoadout>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CharacterLoadout _v;
            _v = global::LOP.MasterData.CharacterLoadout.DeserializeCharacterLoadout(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, CharacterLoadout> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CharacterLoadout> DataList => _dataList;

    public CharacterLoadout GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterLoadout Get(int key) => _dataMap[key];
    public CharacterLoadout this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

