
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// CombatConfig(전역 전투 튜닝, 서버 전용)
/// </summary>
public partial class TbCombatConfig
{
    private readonly System.Collections.Generic.Dictionary<int, CombatConfig> _dataMap;
    private readonly System.Collections.Generic.List<CombatConfig> _dataList;
    
    public TbCombatConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CombatConfig>(n);
        _dataList = new System.Collections.Generic.List<CombatConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CombatConfig _v;
            _v = global::LOP.MasterData.CombatConfig.DeserializeCombatConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, CombatConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CombatConfig> DataList => _dataList;

    public CombatConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CombatConfig Get(int key) => _dataMap[key];
    public CombatConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

