
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// DodgeStage(피하기 스테이지 순서&#183;길이&#183;종류&#183;세기, 클서 공용)
/// </summary>
public partial class TbDodgeStage
{
    private readonly System.Collections.Generic.Dictionary<int, DodgeStage> _dataMap;
    private readonly System.Collections.Generic.List<DodgeStage> _dataList;
    
    public TbDodgeStage(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DodgeStage>(n);
        _dataList = new System.Collections.Generic.List<DodgeStage>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DodgeStage _v;
            _v = global::LOP.MasterData.DodgeStage.DeserializeDodgeStage(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DodgeStage> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DodgeStage> DataList => _dataList;

    public DodgeStage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DodgeStage Get(int key) => _dataMap[key];
    public DodgeStage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

