
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// DodgeConfig(피하기 목숨&#183;판정&#183;위험 튜닝, 클서 공용)
/// </summary>
public partial class TbDodgeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DodgeConfig> _dataMap;
    private readonly System.Collections.Generic.List<DodgeConfig> _dataList;
    
    public TbDodgeConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DodgeConfig>(n);
        _dataList = new System.Collections.Generic.List<DodgeConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DodgeConfig _v;
            _v = global::LOP.MasterData.DodgeConfig.DeserializeDodgeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DodgeConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DodgeConfig> DataList => _dataList;

    public DodgeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DodgeConfig Get(int key) => _dataMap[key];
    public DodgeConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

