
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// FlappyConfig(Flappy Race 튜닝, 클&#183;서 공용)
/// </summary>
public partial class TbFlappyConfig
{
    private readonly System.Collections.Generic.Dictionary<int, FlappyConfig> _dataMap;
    private readonly System.Collections.Generic.List<FlappyConfig> _dataList;
    
    public TbFlappyConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, FlappyConfig>(n);
        _dataList = new System.Collections.Generic.List<FlappyConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            FlappyConfig _v;
            _v = global::LOP.MasterData.FlappyConfig.DeserializeFlappyConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, FlappyConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<FlappyConfig> DataList => _dataList;

    public FlappyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FlappyConfig Get(int key) => _dataMap[key];
    public FlappyConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

