
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// GameMode
/// </summary>
public partial class TbGameMode
{
    private readonly System.Collections.Generic.Dictionary<int, GameMode> _dataMap;
    private readonly System.Collections.Generic.List<GameMode> _dataList;
    
    public TbGameMode(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GameMode>(n);
        _dataList = new System.Collections.Generic.List<GameMode>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GameMode _v;
            _v = global::LOP.MasterData.GameMode.DeserializeGameMode(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, GameMode> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameMode> DataList => _dataList;

    public GameMode GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameMode Get(int key) => _dataMap[key];
    public GameMode this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

