
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// Item
/// </summary>
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<string, Item> _dataMap;
    private readonly System.Collections.Generic.List<Item> _dataList;
    
    public TbItem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, Item>(n);
        _dataList = new System.Collections.Generic.List<Item>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item _v;
            _v = global::LOP.MasterData.Item.DeserializeItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Item> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Item> DataList => _dataList;

    public Item GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item Get(string key) => _dataMap[key];
    public Item this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

