
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// GameMap
/// </summary>
public partial class TbMap
{
    private readonly System.Collections.Generic.Dictionary<int, GameMap> _dataMap;
    private readonly System.Collections.Generic.List<GameMap> _dataList;
    
    public TbMap(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GameMap>(n);
        _dataList = new System.Collections.Generic.List<GameMap>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GameMap _v;
            _v = global::LOP.MasterData.GameMap.DeserializeGameMap(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, GameMap> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameMap> DataList => _dataList;

    public GameMap GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameMap Get(int key) => _dataMap[key];
    public GameMap this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

