
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// PanchigiSetup(인원별 판 구성)
/// </summary>
public partial class TbPanchigiSetup
{
    private readonly System.Collections.Generic.Dictionary<int, PanchigiSetup> _dataMap;
    private readonly System.Collections.Generic.List<PanchigiSetup> _dataList;
    
    public TbPanchigiSetup(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, PanchigiSetup>(n);
        _dataList = new System.Collections.Generic.List<PanchigiSetup>(n);
        for(int i = n ; i > 0 ; --i)
        {
            PanchigiSetup _v;
            _v = global::LOP.MasterData.PanchigiSetup.DeserializePanchigiSetup(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, PanchigiSetup> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PanchigiSetup> DataList => _dataList;

    public PanchigiSetup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PanchigiSetup Get(int key) => _dataMap[key];
    public PanchigiSetup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

