
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// PanchigiConfig(판치기 튜닝)
/// </summary>
public partial class TbPanchigiConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PanchigiConfig> _dataMap;
    private readonly System.Collections.Generic.List<PanchigiConfig> _dataList;
    
    public TbPanchigiConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, PanchigiConfig>(n);
        _dataList = new System.Collections.Generic.List<PanchigiConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            PanchigiConfig _v;
            _v = global::LOP.MasterData.PanchigiConfig.DeserializePanchigiConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, PanchigiConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PanchigiConfig> DataList => _dataList;

    public PanchigiConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PanchigiConfig Get(int key) => _dataMap[key];
    public PanchigiConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

