
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// Queue
/// </summary>
public partial class TbQueue
{
    private readonly System.Collections.Generic.Dictionary<int, Queue> _dataMap;
    private readonly System.Collections.Generic.List<Queue> _dataList;
    
    public TbQueue(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Queue>(n);
        _dataList = new System.Collections.Generic.List<Queue>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Queue _v;
            _v = global::LOP.MasterData.Queue.DeserializeQueue(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Queue> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Queue> DataList => _dataList;

    public Queue GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Queue Get(int key) => _dataMap[key];
    public Queue this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

