
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// SkydiveConfig(스카이다이브 자세&#183;스태미나 튜닝, 클서 공용)
/// </summary>
public partial class TbSkydiveConfig
{
    private readonly System.Collections.Generic.Dictionary<int, SkydiveConfig> _dataMap;
    private readonly System.Collections.Generic.List<SkydiveConfig> _dataList;
    
    public TbSkydiveConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SkydiveConfig>(n);
        _dataList = new System.Collections.Generic.List<SkydiveConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SkydiveConfig _v;
            _v = global::LOP.MasterData.SkydiveConfig.DeserializeSkydiveConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, SkydiveConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SkydiveConfig> DataList => _dataList;

    public SkydiveConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SkydiveConfig Get(int key) => _dataMap[key];
    public SkydiveConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

