
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// Skin
/// </summary>
public partial class TbSkin
{
    private readonly System.Collections.Generic.Dictionary<string, Skin> _dataMap;
    private readonly System.Collections.Generic.List<Skin> _dataList;
    
    public TbSkin(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, Skin>(n);
        _dataList = new System.Collections.Generic.List<Skin>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Skin _v;
            _v = global::LOP.MasterData.Skin.DeserializeSkin(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Skin> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Skin> DataList => _dataList;

    public Skin GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Skin Get(string key) => _dataMap[key];
    public Skin this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

