
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// StatusEffect
/// </summary>
public partial class TbStatusEffect
{
    private readonly System.Collections.Generic.Dictionary<int, StatusEffect> _dataMap;
    private readonly System.Collections.Generic.List<StatusEffect> _dataList;
    
    public TbStatusEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, StatusEffect>(n);
        _dataList = new System.Collections.Generic.List<StatusEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            StatusEffect _v;
            _v = global::LOP.MasterData.StatusEffect.DeserializeStatusEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, StatusEffect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<StatusEffect> DataList => _dataList;

    public StatusEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public StatusEffect Get(int key) => _dataMap[key];
    public StatusEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

